stages:
  - deploy
  - post

before_script:
  - cd $DIR_BACKEND

.default:
  tags:
    - linux
  only:
    - production


deployment:
  extends: .default
  stage: deploy
  script:
    - git pull origin production --no-ff


post_deployment:
  extends: .default
  stage: post
  script:
    - php artisan migrate
    - php artisan cache:clear
    - php artisan route:clear
    - php artisan route:cache
    - php artisan config:clear
    - php artisan config:cache
