stages:
    - deploy

before_script:
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/pipe

deployment:
    stage: deploy
    tags:
        - linux
    script:
        - ssh $ACCESS_SSH "cd $DIR_FRONTEND && git pull origin production --no-ff"
        - ssh $ACCESS_SSH "rm -rf /var/www/html/*"
        - ssh $ACCESS_SSH "cd $DIR_FRONTEND && npm install"
        - ssh $ACCESS_SSH "cd $DIR_FRONTEND && npm run build"
        - ssh $ACCESS_SSH "cd $DIR_FRONTEND && cp -r dist/* /var/www/html/"
        - ssh $ACCESS_SSH "cd $DIR_FRONTEND && rm -rf dist/"
    only:
        - production