stages:
  - deploy


deployment:
  stage: deploy
  tags:
    - linux
  script:
    - cd $DIR_BACKEND && git pull origin production --no-ff
    - cd $DIR_BACKEND && php artisan migrate
    - cd $DIR_BACKEND && php artisan cache:clear
    - cd $DIR_BACKEND && php artisan route:clear
    - cd $DIR_BACKEND && php artisan route:cache
    - cd $DIR_BACKEND && php artisan config:clear
    - cd $DIR_BACKEND && php artisan config:cache
  only:
    - production
