stages:
    - deploy


deployment:
    stage: deploy
    tags:
        - linux
    script:
        - cd $DIR_FRONTEND && git pull origin production --no-ff
        - rm -rf /var/www/html/*
        - cd $DIR_FRONTEND && npm install
        - cd $DIR_FRONTEND && npm run build
        - cd $DIR_FRONTEND && cp -r dist/* /var/www/html/
        - cd $DIR_FRONTEND && rm -rf dist/
    only:
        - production
