stages:
    - deploy
    - post

before_script:
    - cd $DIR_FRONTEND

.default:
    tags:
        - linux
    only:
        - production


deployment:
    extends: .default
    stage: deploy
    script:
        - git pull origin production --no-ff


post_deployment:
    extends: .default
    stage: post
    script:
        - rm -rf /var/www/html/*
        - npm install
        - npm run build
        - cp -r dist/* /var/www/html/
        - rm -rf dist/
